### ISSUE TITLE
Visual Bug when utilizing the animationBar for welded Joint

### ISSUE THREAD

**Issue by AlexG1031** [PMKS-Web/PMKSWeb#101]
![Image](https://github.com/PMKS-Web/PMKSWeb/assets/42430291/60378884-4aea-4f95-bfbb-63b829ae8856)

![Image](https://github.com/PMKS-Web/PMKSWeb/assets/42430291/10ce3631-b949-4291-971d-db8e5b2a78bc)

After creating a four-bar with a welded joint, pressing play, pause, then stop, the welded joint image shows up incorrectly, appearing like this.

**Comment by Kohmei358** [comment]
Merge with #49?

Also GIFs please

Also URL would be great

Also pretty sure this is the issue:
(src/app/model/link.ts Line 604)
``` ts 
    if (!RealLink.isClockwise(this.externalLines[0], this.CoM)) {
      // console.log('Link is not clockwise');
      this.externalLines.reverse();
      //If the link is not clockwise, reverse the order of the external lines
      for (let i = 0; i < this.externalLines.length; i++) {
        const line = this.externalLines[i];
        //Swap start and end positions
        const temp = line.startPosition;
        line.startPosition = line.endPosition;
        line.endPosition = temp;
        line.resetInitialPosition();
      }
    }
```
