### ISSUE TITLE
Cannot add input joint on a grounded prismatic joint

### ISSUE THREAD

**Issue by AlexG1031** [PMKS-Web/PMKSWeb#104]
The user should have the ability to apply an input joint on a grounded prismatic joint. The backend is capable of doing this. If this is not the case, then I can work on implementing this after I finish my task on welded joints.

**Comment by Kohmei358** [comment]
@AlexG1031 I'm gonna send this back to you.

I added the add input option to a slider joint (See branch '#104') on the frontend but it breaks a lot of things. I feel like `toggleInput` needs to get adjusted to target the hidden prismatic joint instead of the visible one? 

Does that make sense?

**Comment by AlexG1031** [comment]
Your comment makes sense to me. I can take a look at this later today and make the desired adjustments. Since you added the contextmenu selection for adding inputJoint for this, I can debug further and see what is causing this problem.

**Comment by Kohmei358** [comment]
@AlexG1031 Thanks for the fix to the function. We still need to rename the function to `setAsInput` instead of toggle and make the edit panel item a button instead of a radio but I added the new SVG to show that the pill is an input.
![Image](https://github.com/PMKS-Web/PMKSWeb/assets/19924289/6516df21-9ee5-438f-b49d-f578c51e5145)

**Comment by AlexG1031** [comment]
Believe we will also need a picture for when the user removes input on a slider crank as well (similar to a revolute joint).

**Comment by Kohmei358** [comment]
Oh you mean the icon for the context menu item?
________________________________

**Comment by AlexG1031** [comment]
Yes.

**Comment by AlexG1031** [comment]
![Image](https://github.com/PMKS-Web/PMKSWeb/assets/42430291/12800909-8797-4fd9-80e7-25fb97d0fc9c)

I added an input with a slider crank. The button appears to be working. However, it is taking the value of the given joint, which will not be the case for a joint connected to a prismatic joint.

**Comment by Kohmei358** [comment]
I'm gonna merge this for now since I'm wating on the new button UI for setting the input (instead of a toggle)
