### ISSUE TITLE
Velocity and Acceleration of a mechanism not appearing

### ISSUE THREAD

**Issue by AlexG1031** [PMKS-Web/PMKSWeb#105]
https://github.com/PMKS-Web/PMKSWeb/assets/42430291/b5a740ca-198b-4aab-9f0e-b1e26d2fdeb8

I found a bug where velocity and acceleration do not show up for the Stephenson III mechanism. I couldn't showcase the entire video since the max length a gif can be is 30 seconds, but believe this should get idea how to recreate the bug. This occurs within my current master branch. 

Once Ansel's code has been merged within master branch, I can copy and paste the URL for this mechanism. 

Not sure if the problem has to do with the simulation class or the UI... 
 
<img width="1756" alt="image" src="https://github.com/PMKS-Web/PMKSWeb/assets/42430291/7ba88925-c0ee-4898-98af-52a81bae6876">

**Comment by AlexG1031** [comment]
The data structure appears correct, so I believe there's something incorrect in the simulator class...

**Comment by AlexG1031** [comment]
This problem is now fixed. KinematicSolver is updated properly.


So here is a demonstration of this updating properly. However, when you delete a joint, the analysis panel is getting called as if the joint is still there.

An easy (bandage) solution is to just make a condition statement asking if mechPart is part of joints. But I don't think this is correct... I feel there is subscriber that should either unsubscribe... What do you think?

**Comment by Kohmei358** [comment]
Interesting, this should be fixed already but it's a one-line fix either way
