### ISSUE TITLE
Multiple Issues with Saving, Opening, and Copy URL

### ISSUE THREAD

**Issue by Kohmei358** [PMKS-Web/PMKSWeb#35]
> Ensure saving and opening functionality supports all new features. Similar to the URL, saving currently does not encode all the information needed to restore the entire linkage state. It is essential to have a seamless save and open experience to prevent user frustration and loss of work. By updating this feature, users can be confident that their work will be preserved and easily accessible when needed.

Your task is to make the 'Share Project' button the toolbar functional again. When the user pushes that button they could get a URL in their clipboard. When they enter this URL into another browser, the entire project state should be recovered from the data in the URL. The URL should be as short as reasonably possible while still supporting up to around 100 joints, links, and forces total.

**Specifically, the URL needs to contain the following info:**
A list of all joints (id, x, y, isGrounded, isInput)
A list of all links (id, joints contained in link, forces contained in link, mass, MOI, sublinks, color)
A list of all forces (id, startCoord, endCoord, isLocal, isFacingOut, magnitude)
A hashmap that maps ids to custom names (in custom-id service)
All settings (Global Units, Angle Units, input speed, input direction, is gravity on, is grid on, is minorGirdLines on?, object scale, currentTimestep from the animation bar)

**These functions will be most relevant:**
src/app/services/url-processor.service.ts ->  constructor()
 src/app/component/toolbar/toolbar.component.ts -> copyURL()

**Other relevant files:**
src/app/model/joint.ts
src/app/model/link.ts
src/app/model/force.ts
src/app/component/toolbar/toolbar.component.html
src/app/component/settings-panel/settings-panel.component.ts
src/app/services/settings.service.ts
src/app/services/custom-id.service.ts

Copy URL does not work and we might need to improve the save file format. For the URL, Ansel has already shortened it significantly but need more testing

**Comment by Kohmei358** [comment]
@AnselChang 
Base on my testing on this site:
https://ansel--pmks.netlify.app

Here is the list of things not working. (roughly ordered by importance)

- [ ] Linkages break when copied at a non-zero time position. Either the joints and links should be saved at a t=0 and always restored to t=0 (easier) or the current timestep should be encoded and loaded (better)
- [ ] Try creating a simulatable valid four-bar (with one ground and one input) if you copy URL and open it is no longer simulatable. (This one might be a little confusing to solve by yourself but start by looking at the linkage table (in the debug panel) and let me know if you need more help
- [ ]  Sliders aren't saved
- [ ]  Welded joints don't get saved at all
- [ ]  Custom Names (Editable through the pencil button on the edit panel) aren't saved at all
- [ ]  Link Colors are not preserved
- [ ] Viewport Position (i.e. zoom and pan CTM)
- [x] All Settings are saved perfectly. Good job!
- [x] Forces look good!

**Comment by AnselChang** [comment]
Everything besides sliders and activeObjectService bug done.
- Working copy on non-zero time positions
- Welded joints
- Custom names
- Link colors

**Comment by Kohmei358** [comment]
**We can talk tomorrow after the scrum but these are the issues I still see:**
Maybe I'm not seeing the newest version?

- Non zero time doesn't save mech position
- Mechanisms are not simulatable (did you merge my solution?)
- This kind of 'partially' welded joints don't work (we need to decide if we will allow this)
![Image](https://github.com/PMKS-Web/PMKSWeb/assets/19924289/b7a9eec1-e57a-4cc7-8b0f-be43bb78ec53)
- I thought we said only alpha numerics for custom names

**Comment by AnselChang** [comment]
-fix welded joint
-alphanumeric restriction html
-merge simulation properly

**Comment by AnselChang** [comment]
Welded joint done. Will work on other two

**Comment by Kohmei358** [comment]
@AnselChang Two things I thought of. Not really a part of the original spec but:

1. Users sometimes copy the URL directly from the browser's URL (not the copy URL button) which gives them an old version of the file if they pasted in a URL this session. Is there a way to clear the URL back to app.pmksplus.com after the linkage is imported so that it will force them to use the 'Copy URL' button?
2. Have you thought of future-proofing the encoding so that we can maintain backward compatibility when we start saving data for synthesis? Are there different types of delimiters for sections like links, and jonts? If we added a single boolean to a joint (for example) would it break all old URLs?

Also, I'm gonna update the linkage library with new links that work when this is finalized so don't worry about that in your PR.

**Comment by rkprad** [comment]
- [ ] The pasted link appears Zoomed in, compared to the original https://deploy-preview-90--pmks.netlify.app/?0P.iO.K,0.101.AB,Trial1,BC,Trial2,CD,Trial3,A,XYZ1,D,XYZ4,B,XYZ2,C,XYZ3.6a,02N9,011k,0.0b,0tX,1l,0.0c,0i-,1wH,0.4d,2aX,0dQ,0..YRab,Fe,Fe,01dL,0W0,c5cae9,a,b,,.YRbc,Fe,Fe,0oG,_0,303e9f,b,c,,.YRcd,Fe,Fe,xn,fS,c5cae9,c,d,,.. 
- [ ] Original vs Share Project
![image](https://github.com/PMKS-Web/PMKSWeb/assets/13953848/3dd1397b-30b2-4262-8c75-bdfd003bb72c)
![image](https://github.com/PMKS-Web/PMKSWeb/assets/13953848/c2cf4d0e-891d-445c-a044-4435dc183149)

**Comment by rkprad** [comment]
- [ ] The path of joints is shown when copying and pasting the URL. Path need not be shown

**Comment by rkprad** [comment]
> 

I am doing all testing in Firefox

**Comment by rkprad** [comment]
Welded Joint: https://deploy-preview-90--pmks.netlify.app/?0P.iO.K,0.101.AB,Trial1,BC,Trial2,CD,Trial3,A,XYZ1,D,XYZ4,B,XYZ2,C,XYZ3.6a,02N9,011k,0.0b,01Bx,02RN,0.0c,0i-,1wH,0.4d,2aX,0dQ,0.8e,02H7,Yj,0.0f,Bu,0rF,0.0g,0_6,0Rn,0.0h,02QA,3Rf,0.4i,1L2,3Q0,0.0j,04fB,1JD,0..YRab,Fe,Fe,01nY,01kY,c5cae9,a,b,,.YRcd,Fe,Fe,xn,fS,c5cae9,c,d,,.YRgh,Fe,Fe,01i8,1Vy,c5cae9,g,h,,.YRhi,Fe,Fe,0Ya,3Qr,303e9f,h,i,,.YRbcefgj,0,0,0,0,0d125a,b,c,e,f,g,e,j,,bcefg,ej.NRbcefg,Fe,Fe,0-G,0Fu,303e9f,b,c,e,f,g,,.NRej,Fe,Fe,03T9,wz,c5cae9,e,j,,.. 

The main app prevents simulation but upon copying and pasting the URL, simulation is permitted. 
Also, the Welded location's path is also being traced. That should be turned off.

**Comment by rkprad** [comment]
> Welded Joint: https://deploy-preview-90--pmks.netlify.app/?0P.iO.K,0.101.AB,Trial1,BC,Trial2,CD,Trial3,A,XYZ1,D,XYZ4,B,XYZ2,C,XYZ3.6a,02N9,011k,0.0b,01Bx,02RN,0.0c,0i-,1wH,0.4d,2aX,0dQ,0.8e,02H7,Yj,0.0f,Bu,0rF,0.0g,0_6,0Rn,0.0h,02QA,3Rf,0.4i,1L2,3Q0,0.0j,04fB,1JD,0..YRab,Fe,Fe,01nY,01kY,c5cae9,a,b,,.YRcd,Fe,Fe,xn,fS,c5cae9,c,d,,.YRgh,Fe,Fe,01i8,1Vy,c5cae9,g,h,,.YRhi,Fe,Fe,0Ya,3Qr,303e9f,h,i,,.YRbcefgj,0,0,0,0,0d125a,b,c,e,f,g,e,j,,bcefg,ej.NRbcefg,Fe,Fe,0-G,0Fu,303e9f,b,c,e,f,g,,.NRej,Fe,Fe,03T9,wz,c5cae9,e,j,,..
> 
> The main app prevents simulation but upon copying and pasting the URL, simulation is permitted. Also, the Welded location's path is also being traced. That should be turned off.

For this six-bar, the zoom percentage is different. The copied link still shows up centered and zoomed up but the object scale still shows up as the original one. 

--
Also, some of these may not be directly connected to this issue but I am just noting all issues.

**Comment by rkprad** [comment]
Kohmei already pointed this out above but the slider does not function https://deploy-preview-90--pmks.netlify.app/?0P.iO.K,8_.101.AB,Trial1,BC,Trial2,CD,Trial3,A,XYZ1,D,XYZ4,B,XYZ2,C,XYZ3.6a,02N9,011k,0.0b,01Bx,02RN,0.0c,0i-,1wH,0.4d,2aX,0dQ,0.8e,02H7,Yj,0.0f,Bu,0rF,0.0g,0_6,0Rn,0.0h,02QA,3Rf,0.0j,04fB,1JD,0.4k,02QA,3Rf,0..YRab,Fe,Fe,01nY,01kY,c5cae9,a,b,,.YRcd,Fe,Fe,xn,fS,c5cae9,c,d,,.YRgh,Fe,Fe,01i8,1Vy,c5cae9,g,h,,.YRbcefgj,0,0,01iN,5W,0d125a,b,c,e,f,g,e,j,,bcefg,ej.YPhk,Fe,0,0,0,,h,k,,.NRbcefg,Fe,Fe,0-G,0Fu,303e9f,b,c,e,f,g,,.NRej,Fe,Fe,03T9,wz,c5cae9,e,j,,..

**Comment by rkprad** [comment]
When a welded joint/link exists in the linkage, such as the image below: 
![image](https://github.com/PMKS-Web/PMKSWeb/assets/13953848/219ffe21-efe6-4f87-abbc-0f8563aaa8e2)

and upon clicking "Share Project" the link "unwelds" as shown in the image below: 
![image](https://github.com/PMKS-Web/PMKSWeb/assets/13953848/2a936281-48bd-40fb-b7eb-1e5b37f5b774)

**Comment by rkprad** [comment]
> When a welded joint/link exists in the linkage, such as the image below: ![image](https://user-images.githubusercontent.com/13953848/243950617-219ffe21-efe6-4f87-abbc-0f8563aaa8e2.png)
> 
> and upon clicking "Share Project" the link "unwelds" as shown in the image below: ![image](https://user-images.githubusercontent.com/13953848/243951356-2a936281-48bd-40fb-b7eb-1e5b37f5b774.png)

this does not happen when the "Share Project" is clicked at the initial position of the linkage

**Comment by Kohmei358** [comment]
@AnselChang Just pinging you to make sure you see Pradeep's comments above

**Comment by Kohmei358** [comment]
Let's talk about this at the scrum. I'm not sure if @rkprad is referring to a viewport issue or the object scale.

**Comment by AnselChang** [comment]
> https://deploy-preview-90--pmks.netlify.app/?0P.iO.K,8_.101.AB,Trial1,BC,Trial2,CD,Trial3,A,XYZ1,D,XYZ4,B,XYZ2,C,XYZ3.6a,02N9,011k,0.0b,01Bx,02RN,0.0c,0i-,1wH,0.4d,2aX,0dQ,0.8e,02H7,Yj,0.0f,Bu,0rF,0.0g,0_6,0Rn,0.0h,02QA,3Rf,0.0j,04fB,1JD,0.4k,02QA,3Rf,0..YRab,Fe,Fe,01nY,01kY,c5cae9,a,b,,.YRcd,Fe,Fe,xn,fS,c5cae9,c,d,,.YRgh,Fe,Fe,01i8,1Vy,c5cae9,g,h,,.YRbcefgj,0,0,01iN,5W,0d125a,b,c,e,f,g,e,j,,bcefg,ej.YPhk,Fe,0,0,0,,h,k,,.NRbcefg,Fe,Fe,0-G,0Fu,303e9f,b,c,e,f,g,,.NRej,Fe,Fe,03T9,wz,c5cae9,e,j,,..

Can you show me this issue with an url? it seems to be working on my end

**Comment by Kohmei358** [comment]
None of the links work for me either so I've been using screenshots lol

**Comment by AnselChang** [comment]
Ah for the urls they work, but you have to include the , and . in the end. Github didn't think they were part of hte url. I might write a patch that removes trailing things

**Comment by Kohmei358** [comment]
[Issue here](https://deploy-preview-90--pmks.netlify.app/?0P.cc.K,0.101.6a,a,0xY,64,0.8b,b,0,1xT,0.0d,d,1ko,WX,0.5e,e,1ko,WX,05T.0f,f,01OC,2dZ,0.0g,g,0N9,3CU,0..YPde,de,Fe,0,0,0,,d,e,,.YRabd,abd,0,0,Cq,17O,0d125a,a,b,d,b,,ab,db.YRbfg,bfg,Fe,Fe,0b7,2bA,c5cae9,b,f,g,,.NRab,ab,Fe,Fe,0Tn,10n,c5cae9,a,b,,.NRdb,db,Fe,Fe,tP,1D-,303e9f,d,b,,..)

Last letter checksum

**Comment by AnselChang** [comment]
Checksum and showCurve done. Is this ready to be merged?

**Comment by AnselChang** [comment]
Forces glitch fixed.
