### ISSUE TITLE
"Input Direction" button does not do anything (Validate Simulator Data from changes)

### ISSUE THREAD

**Issue by KohmeiK** [PMKS-Web/PMKSWeb#46]
![Image](https://user-images.githubusercontent.com/42430291/238389006-a1e32fa0-7933-4566-a0f1-4d0f6ab2cc3a.png)

By default, the input joint is set to travel counterclockwise. When the user clicks on clockwise, nothing happens. What should happen is that clicking clockwise should change the symbol used on the input joint. Also, the direction of the input joint should be set to travel counterclockwise. 

To fix this, the user will have to go through the settings-panel and communicate to new-grid and settingsService.

src/app/services/settings.service.ts (Line 14)
```
  isInputCW = new BehaviorSubject(true);
```

src/app/component/settings-panel/settings-panel.component.ts

**Comment by Kohmei358** [comment]
Same for the gravity toggle

**Comment by AlexG1031** [comment]
Updated this logic, but definitely needs to be re-verified. Believe @JMRhodes03 will need to verify some of this information to make sure that the analysis matches what she has on her MATLAB script. She can help with this once she finishes 92.

**Comment by AlexG1031** [comment]
![Image](https://github.com/PMKS-Web/PMKSWeb/assets/42430291/28bbb81a-33df-4506-bb8f-9542cf0ddf65)

@Kohmei358 Hey, I am curious to hear your thought process for including a button for enabling forces. In my mind, I am not sure if this is needed, nor the logic within it. I image the user can set this value by either left-clicking on the force and selecting the context menu, or right-clicking on it and possibly selecting the desired option within some panel for this. I will bring this up when we meet tonight :P

**Comment by AlexG1031** [comment]
@AnselChang Hey, I will have to ask a favor from you.

In this code, when testing copying URL and pasting it, I find that the settings-panel does not update the global units properly. All the other values within here though work okay. I believe the problem has to be somewhere around here with the picture below...

![Image](https://github.com/PMKS-Web/PMKSWeb/assets/42430291/4465e25b-b211-465f-b518-0a92a1366df1)


When convenient, please check and update this logic so copying and pasting work properly.

**Comment by KohmeiK** [comment]
Related #165
