### ISSUE TITLE
Force Analysis Label Changes to improve clarity

### ISSUE THREAD

**Issue by Kohmei358** [PMKS-Web/PMKSWeb#53]
![Image](https://user-images.githubusercontent.com/42430291/238399843-8823b7ce-352a-4379-8c80-0210b7b61126.png)

The type of analysis is said but we do not know the assumptions that are used within the analysis. We should make it clear the process and assumptions that are used. For example, for force analysis, I believe we assume Newton's second law but do not say so. Also, for kinematics, we also utilize the loop based method instead of the instant center method.

**Comment by rkprad** [comment]
Force Analysis - we use Static equilibrium method and Newton's second law. Both are two different methods, resulting in two different solutions
