### ISSUE TITLE
3 Position Synthesis (Frontend and Data Model)

### ISSUE THREAD

**Issue by KohmeiK** [PMKS-Web/PMKSWeb#61]
The goal of this issue is to implement a 3 Position Synthesis (3 Pose Synthesis) feature for PMKS+. This feature allows the user to enter three poses (x, y, and theta) and the length of the coupler link, and then generate a full four-bar mechanism that satisfies the given poses. A video demonstrating this feature can be found here:

[![3PS Video](https://img.youtube.com/vi/4Gwv9TtsCTo/0.jpg)](https://youtu.be/4Gwv9TtsCTo)

This is a complex task that requires several steps:

1. Define a `Pose` type or class in TypeScript. This type should contain three properties: `x`, `y`, and `theta`, representing the position and orientation of the pose.
2. Implement a function that takes in two `Coord` objects (defined in `src/app/model/coord.ts`) and returns a `Line` object (defined in `src/app/model/line.ts`) that represents the perpendicular bisector of the segment joining the two points. You can use the existing line-line and line-circle intersection functions in `src/app/model/utils.ts`, or write your own if needed.
3. Implement the main synthesis function. This function should take three `Pose` objects and a `length` number as input, and return a list of four `Coord` objects as output. The input poses are assumed to be located at the midpoints of the binary links, and the output coordinates are the four vertices of the four-bar mechanism. The algorithm for finding these coordinates is as follows:

    - For each pose, calculate points A and B, which are the endpoints of the coupler link. These points can be found by adding or subtracting half of the length along the direction perpendicular to the pose orientation.
    - Find two perpendicular bisectors: one for the line segment joining the three A points, and one for the line segment joining the three B points. These bisectors can be found by using the function from step 2 on any pair of points on each segment.
    - Find the intersection point of the two bisectors for the A points. This is the first ground point of the four-bar mechanism. Repeat the same process for the B points to find the second ground point.
    - Return the list of four coordinates in a fixed order: [first ground point, second ground point, first non-grounded point, second non-grounded point].

4. Implement a function that takes in a list of four `Coord` objects and returns a `Mechanism` object (defined in `src/app/model/mechanism/mechanism.ts`) that represents the four-bar mechanism. This function should do the following:

    - Create four `RealJoint` objects (defined in `src/app/model/mechanism/real-joint.ts`) at the four coordinates. Two of them should have `grounded` property set to true, and two of them should have it set to false.
    - Create three `Link` objects (defined in `src/app/model/mechanism/link.ts`) to connect the four joints. Each link should have its `connectedJoints` property set to the list of joints that it contains, and each joint should have its `connectedLinks` property set to the list of links that it belongs to.
    - Select one of the grounded joints as the input joint, and assign it to the `inputJoint` property of the mechanism. The input joint should be the one that allows more range of motion for the mechanism.
    - Return the mechanism object.

5. After this, there will be a couple more frontend steps that I will write later that will need to be added in order to allow the user to input the coupler length and the 3 poses. For testing, feel free to implement basic input boxes or just test with a known set of hard-coded values.

You can use the debug table and the URL processor service (`src/app/services/url-processor.service.ts`) to test and debug the data model (the mechanism object and all it's child properties). You can also refer to this commit by Pradeep, who started working on a similar feature a few months ago:

[ad4da3f](https://github.com/PMKS-Web/PMKSWeb/commit/ad4da3f9bd507ec001db28502385569319f93518)

Good luck and feel free to check in after each step to get feedback if you're unsure in any way!

**Comment by AlexG1031** [comment]
Helpful video showcasing three position analysis we want to replicate: https://www.youtube.com/watch?v=-3LtnaIiMuw

Need to utilize line-line intersection and circle-circle intersection found within utils. These can be found in the utils class (src>app>model>utils) called line_line_intersect and circle_circle_intersect. 

From this method, we will find two ground joints along with the desired links for a four-bar linkage.

**Comment by Kohmei358** [comment]
@JMRhodes03  Steps 1-3 is done by Pradeep already (https://github.com/PMKS-Web/PMKSWeb/commit/ad4da3f9bd507ec001db28502385569319f93518). Please verify the results (just by looking over the logic) but continue from 4.

**Comment by rkprad** [comment]
I will also write a matlab script (and then migrate that to PMKS+ backend) for the following: 
* Comparison of Synthesis results - that is quality of Synthesis results. Possibly doing a RSME (root mean squared error). This would require comparing the orientation of the three positions with that of the generated result. 
* The ability to add two additional links to the generated four-bar to make it a six-bar. That would allow a continuously rotating input.

**Comment by AlexG1031** [comment]
This explained in #112 (https://github.com/PMKS-Web/PMKSWeb/issues/112)

Kohmei will help create a button within synthesis panel. By clicking on this button, synthesis will be done and a 4-bar mechanism will be created. This function will not take any parameters. Inside this function, Pradeep will create the desired poses. These poses will come from his MATLAB script and will be as if these values were pulled from the UI. Based on the functions Pradeep has already created, he will call these methods to determine the ground joints and ultimately the joints and links. These joints and links will be sent to this.mechanismSrv to update the  joints and links. From this, the backend will be fully tested and complete.

**Comment by AlexG1031** [comment]
@AnselChang, Synthesis looks great! Really happy with how synthesis is currently implemented! Looking for functionality and UX issues.

![Image](https://github.com/PMKS-Web/PMKSWeb/assets/42430291/a5ec4c60-0e4b-4a32-8558-bc843d6271ca)


Not 100% sure why but when I go on Edit mode, I see that I cannot add a force to the link... Not sure why this is but users should be able to add forces once they go on Edit mode I believe...

**Comment by AlexG1031** [comment]
@AnselChang quick fix:



![Image](https://github.com/PMKS-Web/PMKSWeb/assets/42430291/386d5007-a1de-4f92-8648-98025536e94c)


Be sure that when you create joints you capitalize the IDs.

**Comment by AnselChang** [comment]
> @AnselChang quick fix:
> 
> ![Image](https://user-images.githubusercontent.com/42430291/261804706-386d5007-a1de-4f92-8648-98025536e94c.png)
> 
> Be sure that when you create joints you capitalize the IDs.

fixed
