### ISSUE TITLE
Position Analysis issues within PMKS+: Length of Links increasing and decreasing

### ISSUE THREAD

**Issue by rkprad** [PMKS-Web/PMKSWeb#92]
This linkage [https://pmksplus.mech.website/?j=A,-3.74,-2.41,AB,R,t,0,0.1,t,%0AB,-2.72,0.91,AB%7CCBD,R,f,0,0.1,f,%0AC,1.58,0.43,CBD%7CCFG,R,f,0,0.1,f,%0AD,-0.24,4.01,DE%7CCBD,R,f,0,0.1,f,%0AE,5.08,5.31,DE%7CFE,R,f,0,0.1,f,%0AF,8.14,3.35,FE%7CCFG,R,f,0,0.1,f,%0AG,7.32,-3.51,CFG,R,t,0,0.1,f,%0A&l=AB,1,1,-3.2300000000000004,-0.75,A%7CB,,l,-2.72,-2.41,-3.74,-2.41,-3.74,0.91,-2.72,0.91%0ADE,1,1,2.42,4.659999999999999,D%7CE,,l,5.08,4.01,-0.24,4.01,-0.24,5.31,5.08,5.31%0ACBD,1,1,-0.3510600176910136,2.6313373415180026,B%7CC%7CD,,et,1.902,0.193,-3.086,0.75,-2.604,5.07,2.384,4.513%0AFE,1,1,6.609999999999999,4.33,E%7CF,,l,8.14,5.31,5.08,5.31,5.08,3.35,8.14,3.35%0ACFG,1,1,6.165062615799421,-1.0419214930288367,C%7CF%7CG,,et,1.182,0.472,8.375,3.674,11.148,-2.556,3.955,-5.757%0A&f=&pp=&tp=&s=10,false,false,cm](url) has increasing/decreasing link length and needs to be fixed.

**Comment by rkprad** [comment]
@JMRhodes03 Hi Jess, It would be good if you could modify the matlab script posted on slack for issue#91 to simulate this linkage. 
That way, you can also learn the circle intersection method implemented within PMKS+ better.

**Comment by Kohmei358** [comment]
Verify this works on the new application by updating the 4bar MATLAB script to support a 6bar.

Then compare these:

1. **Kinematics -** 

Pos, Linear Vel, Linear Accel of every joint
Angle, Ang Vel, Ang Aceel of every link

2.  **Forces**
(Matlab script coming later)

3. **UI** 

Lengths look visually correct on the grid
The Angles of the links look correct

This will eventually become a test case (unit test).

**Comment by JMRhodes03** [comment]
link url no longer works...
