### ISSUE TITLE
Moving tracer joint after adding a welded joint does not update the link shape - Cannot add new link to a compound link

### ISSUE THREAD

**Issue by Kohmei358** [PMKS-Web/PMKSWeb#98]
![Image](https://user-images.githubusercontent.com/42430291/246529103-5d770e2f-bd59-4217-8cbb-d9ff3156b41d.png)

There is a bug where when the user creates a welded joint and then adds a tracer joint, dragging the tracer point does not update the link shape...

I am not sure what is causing this problem... Think this should be a simple fix, most likely a relation not established correctly. Or possibly a conditional statement that has not been accounted for yet. Will have to look into this to determine why this is. 

Edit: The Issue is due to PMKS+ not supporting adding links to a compound link. We need figure out if this should even be allowed

**Comment by Kohmei358** [comment]
I forget who was in charge of this. Alex, just you rigth?

**Comment by AlexG1031** [comment]
Don't think we assigned who was in charge of this. 

Actually, is it possible for you or Ansel to work on this section? The logic for this is that I would want to work on tasks that only I could do, mainly transferring the logic regarding instant centers, sliders, etc from PMKSConversion to PMKSWeb. With regarding with the logic on adding and removing welded joints, I worked on that because we presumed that only I understood the backend within the Simulator class. For this task, this may still require an understanding of the backend but may not exactly be a task that only I can do. 

Curious to hear what you think.

**Comment by Kohmei358** [comment]
More discussion in #49 

Kohmei: 
>All great points! Here's what I'm thinking: The Active (Selected) Object doesn't need to be updated since as long as the main link is selected, you have access to all the subsets by doing link. subsets . A little off topic but the UI I was planning for this would use the related objects panel when a link is selected. Instead of just showing the length for a binary link, if a compound link is selected that is made of two welded binary links, it might show the length of both of those binary links in a editable field.
Anyways, I see two ways to figure out what sublink is selected. One is to use the default HTML object selection detector, which would involve constantly rendering a invisible but clickable outline of each simple link of the compound link over the compound link. (Kinda like what happens now when you select a compound link and the dotted outline shows up). Then when that is right clicked (decorator contextmenu ) you can set the last simple right clicked and keep track of it. Another approach is to use the fuction isPointInsideLInk (src/app/model/link.ts/Line349) which takes in a Coord and RealLink. You could interate over and pass in all the sublinks of the selected link to this function along with the right click point coordinate to figure out which sublink the user meant to click.
Let me know if this is confusing, I'm happy to get on a call to explain if needed.

**Comment by Kohmei358** [comment]
@AlexG1031 Let's talk about this tomorrow, we need to decide the excepted behavior for this to see if we even want to allow this

**Comment by Kohmei358** [comment]
Duplicate of #49
